cmake_minimum_required(VERSION 3.23)

project(test)

add_executable(chapter-05-str-functions chapter-05-str-functions.c)

add_executable(chapter-05-sort chapter-05-sort.c)

add_executable(chapter-06-kw-count chapter-06-kw-count.c)

add_executable(chapter-07-cat chapter-07-cat.c)

add_executable(chapter-07-diff chapter-07-diff.c)