// Code generated by "stringer -type=ValueType --trimprefix ValueType"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValueTypeNone-0]
	_ = x[ValueTypeString-1]
}

const _ValueType_name = "NoneString"

var _ValueType_index = [...]uint8{0, 4, 10}

func (i ValueType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ValueType_index)-1 {
		return "ValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[idx]:_ValueType_index[idx+1]]
}
